files:
  - source: "/test/test.html"
    translation: "/test/%file_name%.%locale%.html"
    dest: "/test/test.webxml"
    type: "webxml"
    languages_mapping:
      locale:
        ru: Russian
        ru2: Russian2
        "": Russian222
    translation_replace: 
      ".en-US" : ""
      "" : "1"
      ".en-USTT" : "test"
      
    
