#
# Choose file structure in crowdin
# e.g. true or false
#
"preserve_hierarchy": true
#
# Files configuration
#
files:
  - source: /src/DDTech.Localization/Account.resx
    translation: /src/DDTech.Localization/%file_name%.%locale%.resx
    dest : /src/DDTech.Localization/Account.csv,
    type: csv,
    scheme: "identifier,source_or_translation"
  - source: /src/DDTech.Localization/Admin.resx
    translation: /src/DDTech.Localization/%file_name%.%locale%.resx
    dest : /src/DDTech.Localization/Admin.csv,
    type: csv,
    scheme: "identifier,source_or_translation"
  - source: /test/test.resx
    translation: /test/%file_name%.%locale%.resx
    dest : /test/test.csv,
    type: csv,
    scheme: "identifier,source_or_translation"
    translation_replace:
      .en-GB:
