files:
  - source: "/test/test.resx"
    translation: "/test/%file_name%.%locale%.resx"
    dest: "/test/test.csv",
    type: "csv",
    languages_mapping:
      locale:
        ru: Russian
    translation_replace: 
      ".en-US" : ""
    
